model: gpt-4o
openai-api-base: http://localhost:8001/v1
openai-api-key: dummy-key
weak-model: gpt-3.5-turbo
stream: false

# 토큰 효율성 설정
map-tokens: 1024
max-chat-history-tokens: 2048
edit-format: diff
auto-commits: true
dirty-commits: false
