model: gpt-4o
openai-api-base: http://localhost:8001/v1
openai-api-key: dummy-key
weak-model: gpt-3.5-turbo
stream: false

# 동적 토큰 설정 (LLM-Proxy에서 가져옴)
map-tokens: 2048
max-chat-history-tokens: 4096
edit-format: diff
auto-commits: true
dirty-commits: false
